name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIRECTORY: dist
      OUTPUT_FILENAME: index.html
    steps:
      - uses: actions/checkout@v2

      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          
      - name: build game
        run: |
          go env -w GO111MODULE=off
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir -p $OUTPUT_DIRECTORY && touch $OUTPUT_DIRECTORY/$OUTPUT_FILENAME
          tweego ./src -o $OUTPUT_DIRECTORY/$OUTPUT_FILENAME

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages
          publish_dir: ./$OUTPUT_DIRECTORY
