name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.13.*'
          check-latest: true
          cache-dependency-path: |
                subdir/go.sum
                tools/go.sum
        # cache-dependency-path: "**/*.sum"

      - name: build game
        run: |
          go get github.com/tmedwards/tweego
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir -p ${{vars.OUTPUT_DIRECTORY}} 
          touch ${{vars.OUTPUT_DIRECTORY}}/${{vars.OUTPUT_FILENAME}}
          tweego ./passages -o ${{vars.OUTPUT_DIRECTORY}}/${{vars.OUTPUT_FILENAME}}

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
         # publish_branch: gh-pages
          publish_dir: ./${{vars.OUTPUT_DIRECTORY}}/